apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: spring-petclinic
spec:
  selector:
    matchLabels:
      app: spring-petclinic
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: springcommunity/spring-framework-petclinic
        ports:
        - name: http
          containerPort: 8080