apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
  namespace: spring-petclinic
  labels:
    app: spring-petclinic
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-petclinic
  type: ClusterIP