apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: '#@ data.values.appName'
  name: '#@ data.values.appName'
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/name: '#@ data.values.appName'
status:
  loadBalancer: {}
