apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-config
  namespace: tanzu-system-grafana
data:
  ldap.toml: |-
    [[servers]]
    host = "ldap-openldap.ldap.svc.cluster.local"
    port = 389
    use_ssl = false
    start_tls = false
    ssl_skip_verify = true

    bind_dn = "cn=admin,dc=example,dc=org"
    bind_password = "C5z6DUTNSMDoiWCHI2GIuSPIzCJt5Zo0"

    search_filter = "(&(objectClass=inetOrgPerson)((cn=%s)))"
    search_base_dns = ["ou=People,dc=example,dc=org"]

    group_search_filter = "(&(objectClass=groupOfNames)(member=uid=%s,ou=People,dc=example,dc=org))"
    group_search_filter_user_attribute = "uid"
    group_search_base_dns = ["ou=Groups,dc=example,dc=org"]

    # Specify names of the ldap attributes your ldap uses
    [servers.attributes]
    email =  "mail"
    name = "givenName"
    surname = "sn"
    username = "uid"


    [[servers.group_mappings]]
    group_dn = "cn=Administrators,dc=example,dc=org"
    org_role = "Admin"
    grafana_admin = true


    [[servers.group_mappings]]
    group_dn = "cn=BlueAdmins,ou=Groups,dc=example,dc=org"
    org_role = "Admin" 
    grafana_admin = true

    [[servers.group_mappings]]
    group_dn = "cn=GreenAdmins,ou=Groups,dc=example,dc=org"
    org_role = "Editor"

    [[servers.group_mappings]]
    group_dn = "*"
    org_role = "Viewer"
