namespace: tanzu-system-grafana

grafana:
  deployment:
    replicas: 1
    containers:
      resources: {}
    podAnnotations: {}
    podLabels: {}
    k8sSidecar:
      containers:
        resources: {}
  service:
    type: LoadBalancer
    port: 80
    targetPort: 3000
    labels: {}
    annotations: {}
  config:
    grafana_ini: |
      [analytics]
      check_for_updates = false
      [grafana_net]
      url = https://grafana.com
      [log]
      mode = console
      [paths]
      data = /var/lib/grafana/data
      logs = /var/log/grafana
      plugins = /var/lib/grafana/plugins
      provisioning = /etc/grafana/provisioning
      [auth.ldap]
      # Set to `true` to enable LDAP integration (default: `false`)
      enabled = true

      # Path to the LDAP specific configuration file (default: `/etc/grafana/ldap.toml`)
      config_file = /etc/grafana/ldap.toml

      # Allow sign-up should be `true` (default) to allow Grafana to create users on successful LDAP authentication.
      # If set to `false` only already existing Grafana users will be able to login.
      allow_sign_up = true
    datasource_yaml: |-
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: prometheus-server.tanzu-system-monitoring.svc.cluster.local
          access: proxy
          isDefault: true
    dashboardProvider_yaml: |-
      apiVersion: 1
      providers:
        - name: 'sidecarDashboardProvider'
          orgId: 1
          folder: ''
          folderUid: ''
          type: file
          disableDeletion: false
          updateIntervalSeconds: 10
          allowUiUpdates: false
          options:
            path: /tmp/dashboards
            foldersFromFilesStructure: true
  pvc:
    annotations: {}
    storageClassName: null
    accessMode: ReadWriteOnce
    storage: "2Gi"
  secret:
    type: "Opaque"
    admin_user: "YWRtaW4="
    admin_password: "YWRtaW4="

ingress:
  enabled: true
  virtual_host_fqdn: "grafana.10.220.2.199.sslip.io"
  prefix: "/"
  servicePort: 80
