apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: kctrl-package.demo.kearos.net.0.0.0
spec:
  refName: kctrl-package.demo.kearos.net
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: kctrl-package.demo.kearos.net
spec:
  displayName: kctrl-package
  longDescription: kctrl-package.demo.kearos.net
  shortDescription: kctrl-package.demo.kearos.net
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: kctrl-package
spec:
  packageRef:
    refName: kctrl-package.demo.kearos.net
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kctrl-dev-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
