apiVersion: supply-chain.apps.tanzu.vmware.com/v1alpha1
kind: SupplyChain
metadata:
    name: appbuildv3
spec:
    defines:
        group: supplychains.tanzu.vmware.com
        kind: AppBuildV3
        plural: appbuildv3s
        version: v1alpha1
    description: Supply chain that pulls the source code from Git repository, builds it using buildpacks and package the output as Carvel package.
    stages:
        - componentRef:
            name: source-git-provider-1.0.1
          name: source-git-provider
        - componentRef:
            name: buildpack-build-1.0.0
          name: buildpack-build
        - componentRef:
            name: conventions-1.0.0
          name: conventions
        - componentRef:
            name: app-config-server-1.0.0
          name: app-config-server
        - componentRef:
            name: carvel-package-1.0.0
          name: carvel-package
        - componentRef:
            name: git-writer-pr-1.0.2
          name: git-writer-pr
