apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: cncf-demo.joostvdg.github.com.0.0.0
spec:
  refName: cncf-demo.joostvdg.github.com
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: cncf-demo.joostvdg.github.com
spec:
  displayName: cncf-demo
  longDescription: cncf-demo.joostvdg.github.com
  shortDescription: cncf-demo.joostvdg.github.com

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: cncf-demo
spec:
  packageRef:
    refName: cncf-demo.joostvdg.github.com
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: cncf-demo-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
